<?php return array (
  'accepted' => 'Le :attribute doit être accepté.',
  'active_url' => 'Le :attribute n\'est pas une URL valide.',
  'after' => 'Le :attribute doit être une date postérieure à :date.',
  'after_or_equal' => 'Le champ :attribute doit être une date postérieure ou égale au :date',
  'alpha' => 'Le :attribute ne peut contenir que des lettres.',
  'alpha_dash' => 'Le :attribute ne peut contenir que des lettres, des chiffres et des tirets.',
  'alpha_num' => 'Le :attribute ne peut contenir que des lettres et des chiffres.',
  'array' => 'Le :attribute doit être un tableau.',
  'before' => 'Le :attribute doit être une date antérieure à :date.',
  'before_or_equal' => 'Le champ :attribute doit être une date antérieure ou égale au :date',
  'between' => 
  array (
    'numeric' => 'Le :attribut doit contenir entre :min et :max.',
    'file' => 'Le :attribut doit contenir entre :min et :max kilo-octets.',
    'string' => 'Le texte :attribute doit contenir entre :min et :max caractères.',
    'array' => 'Le :attribute doit contenir entre :min et :max éléments.',
  ),
  'boolean' => 'Le :attribute doit être vrai ou faux.',
  'confirmed' => 'La confirmation de :attribute ne correspond pas.',
  'date' => 'Le :attribute n\'est pas une date valide.',
  'date_format' => 'Le :attribute ne correspond pas au format :format.',
  'different' => 'Le :attribute et :other doivent être différents.',
  'digits' => 'Le :attribute doit contenir :digits chiffres.',
  'digits_between' => 'Le :attribute doit contenir entre :min et :max chiffres.',
  'dimensions' => 'Le :attribute a des dimensions d\'image non valides.',
  'distinct' => 'Le champ :attribute a une valeur en double.',
  'email' => 'Le :attribute doit être une adresse courriel valide.',
  'exists' => 'L\'attribut :attribute sélectionné n\'est pas valide.',
  'file' => ':attribute doit être un fichier.',
  'filled' => 'Le champ :attribute est obligatoire.',
  'image' => ':attribute doit être une image.',
  'in' => 'L\'attribut :attribute sélectionné n\'est pas valide.',
  'in_array' => 'Le champ :attribute n\'existe pas dans :other.',
  'integer' => 'Le :attribute doit être un nombre entier.',
  'ip' => 'L\' :attribute doit être une adresse IP valide.',
  'json' => 'L\' :attribute doit être une chaîne JSON valide.',
  'max' => 
  array (
    'numeric' => 'L\' :attribute ne peut pas être supérieur à :max.',
    'file' => 'L\' :attribute ne peut pas être supérieur à :max kilo-octets.',
    'string' => 'L\' :attribute ne peut pas être supérieur à :max caractères.',
    'array' => 'L\' :attribute ne peut pas avoir plus de :max éléments.',
  ),
  'mimes' => 'L\' :attribute doit être un fichier de type : :values.',
  'mimetypes' => 'L\' :attribute doit être un fichier de type : :values.',
  'min' => 
  array (
    'numeric' => 'L\' :attribute doit être d\'au moins :min.',
    'file' => 'L\' :attribute doit être d\'au moins :min kilo-octets.',
    'string' => 'L\' :attribute doit contenir au moins :min caractères.',
    'array' => 'L\' :attribute doit avoir au moins :min éléments.',
  ),
  'not_in' => 'L\' :attribute sélectionné n\'est pas valide.',
  'numeric' => 'L\' :attribute doit être un nombre.',
  'present' => 'Le champ :attribute doit être présent.',
  'regex' => 'L\' :attribute le format n\'est pas valide.',
  'required' => 'Le champ :attribute est obligatoire.',
  'required_if' => 'Le champ :attribute est requis lorsque :other est :value.',
  'required_unless' => 'Le champ :attribute est obligatoire, sauf si :other est dans les :values.',
  'required_with' => 'Le champ :attribute est requis lorsque :values est présente.',
  'required_with_all' => 'Le champ :attribute est requis lorsque :values est présente.',
  'required_without' => 'Le champ :attribute est requis lorsque :values n\'est pas présente.',
  'required_without_all' => 'Le champ :attribute est requis lorsqu\'aucune des :values sont présentes.',
  'same' => 'Le :attribute et :other doivent correspondre.',
  'size' => 
  array (
    'numeric' => 'Le :attribute doit être de :size.',
    'file' => 'Le :attribute doit être de :size kilo-octets.',
    'string' => 'Le :attribute doit être de :size caractères.',
    'array' => 'Le :attribute doit contenir :size éléments.',
  ),
  'string' => 'Le :attribute doit être une chaîne.',
  'timezone' => 'Le :attribute doit être une zone valide.',
  'unique' => ':attribute est déjà pris.',
  'uploaded' => ':attribute n\'a pas pu être téléchargé.',
  'url' => 'Le format :attribute n\'est pas valide.',
);
